# Generated by Django 4.0.4 on 2022-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_charts_question_alter_room_code_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='charts_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField(blank=True, null=True)),
                ('Input', models.IntegerField(default=1)),
            ],
        ),
    ]
