# Generated by Django 4.0.6 on 2022-07-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_charts_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stack', models.CharField(max_length=50, unique=True)),
                ('framework', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
